### ISSUE TITLE
VLC is unable to open the MRL

### ISSUE THREAD

**Issue by 51bitquant** [zesicus/WeLSee#1]
不知你用的VLC 是哪个版本？播放凤凰中文是播放不了的。谢谢。

**Comment by zesicus** [comment]
@ramoslin02 不好意思现在才看到，跟VLC版本是没有关系的，应该是视频地址失效了。

**Comment by 51bitquant** [comment]
请问你这个视频地址是怎么获得的？能请教一下吗？

**Comment by zesicus** [comment]
@ramoslin02 从网上找到的，零星收集到的，并不好找这些，而且有些地址失效的很快。
