### ISSUE TITLE
player.h 中 id方法 Xcode提示我 view 应该预计一个类型

### ISSUE THREAD

**Issue by shijianmianju** [zesicus/WeLSee#2]
如题  player.h中 那两个添加view的方法 Xcode报错  具体的我可以给你邮件 但是不知道你的邮箱  我这有截图 但是guthub的issues好像不支持

**Comment by zesicus** [comment]
@yhdaren 是可以支持的，文本框下面 "selecting them" 点进去选择图片就好。
可加QQ交流 756798683

**Comment by zesicus** [comment]
Have been fix this issue, I forgot import the UIKit in Player.h file 😓
