### ISSUE TITLE
点击直播页面会崩溃

### ISSUE THREAD

**Issue by SmallwolfiOS** [zesicus/WeLSee#3]
安装好VLCMobileKit.framework点击直播页面会崩溃

**Comment by zesicus** [comment]
不会崩溃吧，我这边播放没遇到这样的问题，是不是你VLC导入的有问题

**Comment by SmallwolfiOS** [comment]
我利用cocoapods 导入的，但是我代码改为直接触摸屏幕（隐藏掉类似CollectionView的代码）出发播放事件就没有问题，完全可以播放。但是不改代码的话，直接点击就是会崩溃，崩到touch Event  那个地方

**Comment by zesicus** [comment]
我这里并没有崩溃过……反正提供的是一个用VLC播放rtsp的思路，VLC用起来就好了
