### ISSUE TITLE
放进2.1的MobileVLCKit.framework 编译不起来 简直了。。。

### ISSUE THREAD

**Issue by YelCode** [zesicus/WeLSee#4]

**Comment by YelCode** [comment]
ld: truncated fat file. Slice from 737037392 to 938667200 is past end of file with length 660865024 file '/Users/hbn/Downloads/WeLSee-master/We'll see/MobileVLCKit.framework/MobileVLCKit' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by zesicus** [comment]
很抱歉出现了这样的问题，请检查一下build settings -> Framework Search Paths 的路径是否正确，如果还出现此类问题建议删除MobileVLCKit.framework以及关联库并采用Pods重新安装。
