### ISSUE TITLE
怎么能让APP出现在itunes 上进行文件传输的？

### ISSUE THREAD

**Issue by ZackKingS** [zesicus/WeLSee#6]
怎么能让APP出现在itunes 上进行文件传输的？
![1111](https://user-images.githubusercontent.com/16434035/29815878-ca8e8fc6-8ce4-11e7-9c81-a8441827053f.png)

**Comment by zesicus** [comment]
Bing一下嘛pal，仅仅Info.plist里面加一个键值对就可以了
